---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: kubernetes
      when: configure_kubernetes
      tags: ['kubernetes', 'containers']
  tasks:
    - include_tasks: tasks/ansible-setup.yml
