---
- hosts: all
  gather_facts: yes
  vars:
    bash_it:
      enable: True
    tmux:
      enable: True
    vim:
        enable: True
    htop:
        enable: True
    screen:
      enable: True
    zsh:
      enable: False
    kubernetes:
      enable: True
    docker:
      enable: True

    # aws:
    #   enable: False
    # hashicorp:
    #   enable: True
    # cloud9:
    #   enable: True
    # vscode:
    #   enable: True
    # language_python:
    #   enable: tasdrue

  roles:
  - baseline
  # - docker
  # - kubernetes
  #   #  - baseline
  #   #  - aws
  #   #  - hashicorp
